### ISSUE TITLE
Django Rest Framework Integration

### ISSUE THREAD

**Issue by pmburu** [bdelate/django-flutterwave#1]
Hello @bdelate,

Thank you for this nicely done code. I would like to know how to integrate it with my DRF API.
I a using rave to handle user subscriptions and payments that are then projected via a react app.

How do I go about it after installation? Do I still create my own membership models etc?

Thanks

**Comment by bdelate** [comment]
Hi.

At this time DRF is not supported however it is something that will be added at some point in the future. There is currently no timeline on when this will be done.

Pull requests are welcome in the interim.

**Comment by pmburu** [comment]
Thanks @bdelate ,

I will be Looking forward to  seeing the DRF version

**Comment by bdelate** [comment]
@pmburu The latest version of this package now supports initiating payments via an API based app (eg: Vue, React etc). Please refer to the Readme for information on implementing this.

**Comment by pmburu** [comment]
Thank you very much @bdelate, I'll keep you updated with latest developments.
